import turtle
greg = turtle.Turtle()
window = turtle.Screen()
def the_eyeglass():
  greg.penup()
  greg.left(180)
  greg.forward(80)
  greg.left(180)
  greg.pendown()
  greg.fillcolor("brown")
  greg.begin_fill()
  greg.circle(50)
  greg.end_fill()
  greg.penup()
  greg.left(90)
  greg.forward(10)
  greg.right(90)
  greg.pendown()
  greg.fillcolor("white")
  greg.begin_fill()
  greg.circle(40)
  greg.end_fill()
  greg.penup()
def bridge():
  for i in range(90):
    greg.left(1.6)
    greg.forward(0.9)
def main():
  greg.shape("turtle")
  greg.color("purple")
  window.colormode(255)
  window.bgcolor("yellow")
  greg.speed(1)
  greg.fillcolor("red")
  greg.penup()
  greg.begin_fill()
  greg.goto(-110,-190)
  for i in range(2):
    greg.fd(200)
    greg.circle(100,90)
    greg.fd(180)
    greg.circle(100,90)
  greg.end_fill()
  greg.goto(0,5)
  the_eyeglass()
  greg.goto(140,5)
  the_eyeglass()
  greg.left(90)
  greg.forward(40)
  greg.left(90)
  greg.forward(40)
  greg.right(90)
  greg.pendown()
  greg.color("brown")
  greg.right(180)
  greg.forward(20)
  greg.right(180)
  greg.pensize(6)
  bridge()
  greg.right(55)
  greg.fillcolor("black")
  greg.penup()
  greg.goto(-202,120)
  greg.pendown()
  greg.color("black")
  greg.begin_fill()
  greg.left(180)
  greg.forward(390)
  greg.left(90)
  greg.circle(85,90)
  greg.forward(230)
  greg.circle(85,90)
  greg.end_fill()
  greg.penup()
  greg.color("orange")
  greg.goto(-10,-15)
  greg.right(45)
  greg.pendown()
  greg.forward(55)
  greg.left(140)
  greg.forward(45)
  greg.left(90)
  greg.forward(37)
  greg.penup()
  greg.color(255,51,51)
  greg.goto(95,-40)
  greg.right(180)
  greg.pendown()
  greg.forward(65)
  greg.left(130)
  greg.forward(77.5)
  greg.penup()
  greg.goto(-125,-40)
  greg.right(140)
  greg.pendown()
  greg.forward(65)
  greg.right(130)
  greg.forward(77.5)
  greg.right(45)
  greg.penup()
  greg.goto(-235,380)
  greg.color(160,160,160)
  greg.write("Don't Touch the Spikes",font=("Verdana", 30 , "normal"))
  greg.hideturtle()
  window.exitonclick()

main()
